### PR TITLE
Submodules and Documentation.

### PR DESCRIPTION
**Pull request by andynu**
Hello Albert,

It begins! I haven't done much, but please read through the commits. The most notable thing is conversion from folders to git submodules for the three dependent projects, and the beginnings of a readme.

I don't know how familiar you are with git, but I've added the TALENPWMScorer binary and the private folder to the .gitignore file so they won't get committed by mistake. One should never commit generated files (unless they are very expensive to generate), and obviously you asked me to keep the example stuff private so I've isolated it.
## 

Andy

### CODE REVIEW

**Comment by albertwcheng** [comment]
Hi Andy,

The D to the left is for "deletion", A for "addition? What does M
stands for? Does it mean that the original CppUtilClasses were deleted
from the repository but added back as a submodule?

Also, is there a tool for quickily compare differences between two branches?

Thanks
Albert

On Wed, Jul 11, 2012 at 4:40 PM, Andrew Nutter-Upham
reply@reply.github.com
wrote:

> Hello Albert,
> 
> It begins! I haven't done much, but please read through the commits. The most notable thing is conversion from folders to git submodules for the three dependent projects, and the beginnings of a readme.
> 
> I don't know how familiar you are with git, but I've added the TALENPWMScorer binary and the private folder to the .gitignore file so they won't get committed by mistake. One should never commit generated files (unless they are very expensive to generate), and obviously you asked me to keep the example stuff private so I've isolated it.
> 
> ## 
> 
> Andy
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/andynu/TALENPWMScorer master
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/albertwcheng/TALENPWMScorer/pull/1
> 
> -- Commit Summary --
> - remove statically imported submodules
> - Convert dependent projects to git submodules
> - Use markdown for the README.
> - begin to document the build/run process
> - ignore the binary
> - ignore the private directory
> 
> -- File Changes --
> 
> A .gitignore (2)
> A .gitmodules (9)
> A CppBioClasses (1)
> D CppBioClasses/BamUtil.h (433)
> D CppBioClasses/FastaFile.h (78)
> D CppBioClasses/Gff.cpp (0)
> D CppBioClasses/Gff.h (528)
> D CppBioClasses/Makefile (0)
> D CppBioClasses/Nucleic.h (165)
> D CppBioClasses/README (0)
> D CppBioClasses/TestBamUtil.cpp (28)
> D CppBioClasses/TestGff.cpp (39)
> D CppBioClasses/make.sh (13)
> A CppUtilClasses (1)
> D CppUtilClasses/Array.h (375)
> D CppUtilClasses/ArrayTest.cpp (40)
> D CppUtilClasses/Commonf.h (467)
> D CppUtilClasses/ConfigFile.cpp (145)
> D CppUtilClasses/ConfigFile.h (253)
> D CppUtilClasses/Matrix.h (261)
> D CppUtilClasses/README (0)
> D CppUtilClasses/RandomAccessFile.cpp (130)
> D CppUtilClasses/RandomAccessFile.h (51)
> D CppUtilClasses/SmartPtr.h (109)
> D CppUtilClasses/SortPair.h (108)
> D CppUtilClasses/SortPairExample.cpp (38)
> D CppUtilClasses/StringUtil.h (685)
> D CppUtilClasses/SuperConfigFile.cpp (266)
> D CppUtilClasses/SuperConfigFile.h (79)
> D CppUtilClasses/SystemUtil.h (52)
> D CppUtilClasses/Vector2Array.h (49)
> D CppUtilClasses/makeExample.sh (4)
> D README (0)
> A README.md (62)
> M bedSeq (2)
> 
> -- Patch Links --
> 
>   https://github.com/albertwcheng/TALENPWMScorer/pull/1.patch
>   https://github.com/albertwcheng/TALENPWMScorer/pull/1.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/albertwcheng/TALENPWMScorer/pull/1

## 

Albert W. Cheng
PhD candidate
Burge and Jaenisch Labs,
Computational & Systems Biology,
and Whitehead Institute for Biomedical Research,
Massachusetts Institute of Technology
Cambridge, MA, USA
http://www.albertcheng.info

**Comment by andynu** [comment]
Albert,

M stands for modified.

Yep. I deleted all three of those and re-added them as sub modules. So if there are differences that you had not committed back into the other three projects, they won't be present.

When you say a tool to easily diff two branches... Do you mean here on github? Do you mean my my changes vs. your master? If so that's what the diff tab above is. Git's commandline does diffing too. for example if you are on the master branch and want to diff against a branch named 'dev': git diff dev. Depending on your OS I have some recommendations. In windows araxis merge is great. in linux Meld is good. I don't have OSX recommendations yet.

**Comment by albertwcheng** [comment]
Hi Andy,

I have this error:

remote: Counting objects: 18, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 17 (delta 6), reused 16 (delta 5)
Unpacking objects: 100% (17/17), done.
From https://github.com/andynu/TALENPWMScorer
- branch            master     -> FETCH_HEAD
  CONFLICT (directory/file): There is a directory with name
  CppBioClasses in HEAD. Adding CppBioClasses as
  CppBioClasses~e7610eeaf03a464ce9b2bc293af6362b7b979071
  Removing CppBioClasses/BamUtil.h
  Removing CppBioClasses/FastaFile.h
  Removing CppBioClasses/Gff.cpp
  Removing CppBioClasses/Gff.h
  Removing CppBioClasses/Makefile
  Removing CppBioClasses/Nucleic.h
  Removing CppBioClasses/README
  Removing CppBioClasses/TestBamUtil.cpp
  Removing CppBioClasses/TestGff.cpp
  Removing CppBioClasses/make.sh
  CONFLICT (directory/file): There is a directory with name
  CppUtilClasses in HEAD. Adding CppUtilClasses as
  CppUtilClasses~e7610eeaf03a464ce9b2bc293af6362b7b979071
  Removing CppUtilClasses/Array.h
  Removing CppUtilClasses/ArrayTest.cpp
  Removing CppUtilClasses/Commonf.h
  Removing CppUtilClasses/ConfigFile.cpp
  Removing CppUtilClasses/ConfigFile.h
  Removing CppUtilClasses/Matrix.h
  Removing CppUtilClasses/README
  CONFLICT (delete/modify): CppUtilClasses/RandomAccessFile.cpp deleted
  in e7610eeaf03a464ce9b2bc293af6362b7b979071 and modified in HEAD.
  Version HEAD of CppUtilClasses/RandomAccessFile.cpp left in tree.
  Removing CppUtilClasses/RandomAccessFile.h
  Removing CppUtilClasses/SmartPtr.h
  Removing CppUtilClasses/SortPair.h
  Removing CppUtilClasses/SortPairExample.cpp
  Removing CppUtilClasses/StringUtil.h
  Removing CppUtilClasses/SuperConfigFile.cpp
  Removing CppUtilClasses/SuperConfigFile.h
  Removing CppUtilClasses/SystemUtil.h
  Removing CppUtilClasses/Vector2Array.h
  Removing CppUtilClasses/makeExample.sh
  Removing README
  Automatic merge failed; fix conflicts and then commit the result.

How do I fix it?

Thanks
Albert

On Mon, Jul 16, 2012 at 11:20 AM, Andrew Nutter-Upham
reply@reply.github.com
wrote:

> Albert,
> 
> M stands for modified.
> 
> Yep. I deleted all three of those and re-added them as sub modules. So if there are differences that you had not committed back into the other three projects, they won't be present.
> 
> When you say a tool to easily diff two branches... Do you mean here on github? Do you mean my my changes vs. your master? If so that's what the diff tab above is. Git's commandline does diffing too. for example if you are on the master branch and want to diff against a branch named 'dev': git diff dev. Depending on your OS I have some recommendations. In windows araxis merge is great. in linux Meld is good. I don't have OSX recommendations yet.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/albertwcheng/TALENPWMScorer/pull/1#issuecomment-7009006

## 

Albert W. Cheng
PhD candidate
Burge and Jaenisch Labs,
Computational & Systems Biology,
and Whitehead Institute for Biomedical Research,
Massachusetts Institute of Technology
Cambridge, MA, USA
http://www.albertcheng.info

**Comment by andynu** [comment]
So you have made changes since the version that was available on github. You should always make sure you're fully committed before starting a merge like this. If you are completely merged, that it is probably that those changes had not been pushed to the git repo before I did my changes. If that's the case then please git push and I'll rebase the merge after those changes and re-submit a new pull request for you.

If you had a bunch of local changes  that were not committed then ... you should commit those somewhere. My recommendation is moving any changes in those three sub projects into those projects, so that we can continue with the deleting of them from this project. Please be careful! I don't want you to loose any work.

If you are SURE that all those changes are saved elsewhere then you can continue with the merge with the following steps. Please note that this will destroy any local changes to those three subfolders.

```
rm -rf CppUtilClasses
git add CppUtilClasses
git commit
```

So that will blow away your local changes to all the files in the CppUtilClasses and continue the merge.

**Pull request closed without merging**
